VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "server01" do |server01|
    server01.vm.box = "ubuntu/trusty64"
    server01.vm.hostname = "server01"
    server01.vm.network :private_network, ip: "10.11.12.51"
    server01.vm.network :private_network, ip: "192.168.12.51", virtualbox__intnet: true
  end

  config.vm.define "server02" do |server02|
    server02.vm.box = "ubuntu/trusty64"
    server02.vm.hostname = "server02"
    server02.vm.network :private_network, ip: "10.11.12.52"
    server02.vm.network :private_network, ip: "192.168.12.52", virtualbox__intnet: true
  end

  config.vm.define "server03" do |server03|
    server03.vm.box = "ubuntu/trusty64"
    server03.vm.hostname = "server03"
    server03.vm.network :private_network, ip: "10.11.12.53"
    server03.vm.network :private_network, ip: "192.168.12.53", virtualbox__intnet: true
  end

  config.vm.define "server04" do |server04|
    server04.vm.box = "ubuntu/trusty64"
    server04.vm.hostname = "server04"
    server04.vm.network :private_network, ip: "10.11.12.54"
    server04.vm.network :private_network, ip: "192.168.12.54", virtualbox__intnet: true
  end

  config.vm.define "db01" do |db01|
    db01.vm.box = "ubuntu/trusty64"
    db01.vm.hostname = "db01"
    db01.vm.network :private_network, ip: "10.11.12.61"
    db01.vm.network :private_network, ip: "192.168.12.61", virtualbox__intnet: true
  end

  config.vm.define "db02" do |db02|
    db02.vm.box = "ubuntu/trusty64"
    db02.vm.hostname = "db02"
    db02.vm.network :private_network, ip: "10.11.12.62"
    db02.vm.network :private_network, ip: "192.168.12.62", virtualbox__intnet: true
  end

  config.vm.define "db03" do |db03|
    db03.vm.box = "ubuntu/trusty64"
    db03.vm.hostname = "db03"
    db03.vm.network :private_network, ip: "10.11.12.63"
    db03.vm.network :private_network, ip: "192.168.12.63", virtualbox__intnet: true
  end

  config.vm.define "db04" do |db04|
    db04.vm.box = "ubuntu/trusty64"
    db04.vm.hostname = "db04"
    db04.vm.network :private_network, ip: "10.11.12.64"
    db04.vm.network :private_network, ip: "192.168.12.64", virtualbox__intnet: true
  end

  config.vm.define "db05" do |db05|
    db05.vm.box = "ubuntu/trusty64"
    db05.vm.hostname = "db05"
    db05.vm.network :private_network, ip: "10.11.12.65"
    db05.vm.network :private_network, ip: "192.168.12.65", virtualbox__intnet: true
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "320"]
  end
end
